bpmn_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
                  path("",
                       RedirectView.as_view(url="/workflow/compra", permanent=False)),
                  path("workflow/",
                       include("workflow.urls", namespace='workflow')),
                  path("accounts/", include("core.urls", namespace='core')),
                  path("accounts/", include("django.contrib.auth.urls")),
                  path("api-auth/", include("rest_framework.urls")),
                  path("ee3040565933ca2fecc69739fbf053c6/", admin.site.urls),
                  path("rosetta/", include("rosetta.urls")),
              ] + static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import include, path
from rest_framework import routers
from django.contrib.auth.views import LogoutView
from core.api.views import UserViewSet
from django.views import generic

from . import views

router = routers.DefaultRouter()
router.register("", UserViewSet)

app_name = 'core'

urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("password_reset/", views.PasswordReset.as_view(),
         name="password_reset"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path("users/", include(router.urls)),
    path("manage_account/", generic.TemplateView.as_view(
        template_name="core/manage account.html"), name="manage_account"),
    path("help/", generic.TemplateView.as_view(template_name="core/help.html"),
         name="help"),
    path("settings/", generic.TemplateView.as_view(template_name="core/settings.html"),
         name="settings")
]

templates/base.html
{% load i18n static %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
        <link href="{% static 'img/favicon.png' %}" rel="shortcut icon">
        <!--Let browser know website is optimized for mobile-->
        {% block turbolinks-cache-control %}
            <meta name="turbolinks-cache-control" content="no-cache">{% endblock %}
        <title>{% block title %}{% endblock title %}</title>
        <!--Import CSS-->
        {% block css %}{% include 'includes/css_includes.html' %}{% endblock css %}
        {% block extrahead %}{% endblock extrahead %}
    {% endblock head %}
</head>
<body>
{% block body %}
    <header>
        {% block header %}
            <!-- NAVBAR STRUCTURE -->
            <div class="navbar-fixed">
                <nav class="navbar teal darken-2">
                    <div class="nav-wrapper">
                        <ul id="nav-mobile" class="right">
                            <li>
                                <a id="notifications" class="waves-effect waves-light waves-block">
                                    <i class="material-icons">notifications_none
                                        <small class="notification-badge">5</small>
                                    </i>
                                </a>

                                <!-- Dropdown Notifications Structure -->
                                <ul id="dropdown-notifications" class="dropdown-content">
                                    <li>
                                        <div class="row">
                                            <div class="col s8"><h6>Notificaciones</h6></div>
                                            <div class="col s4">
                                                <div class="col s12 input-field">
                                                    <select>
                                                        <option value="1">Todas</option>
                                                        <option value="3">No Leído</option>
                                                        <option value="2">Leído</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#" class="black-text">
                                            <span class="material-icons icon-bg-circle red">settings</span>
                                            Notificacion de Sistema
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="black-text">
                                            <span class="material-icons icon-bg-circle red">settings</span>
                                            Notificacion de Sistema</a>
                                    </li>
                                    <li>
                                        <a href="#" class="black-text">
                                            <span class="material-icons icon-bg-circle red">settings</span>
                                            Notificacion de Sistema</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="dropdown-trigger waves-effect waves-light waves-block" href="#!"
                                   data-target="dropdown-user-options">
                                    {{ request.user.get_full_name }}
                                    <i class="material-icons right">arrow_drop_down</i>
                                </a>

                                <!-- Dropdown User Options Structure -->
                                <ul id="dropdown-user-options" class="dropdown-content dropdrown-user">
                                    <li><a href="{% url 'core:manage_account' %}">Administrar Cuenta</a></li>
                                    <li><a href="{% url 'core:help' %}">Ayuda</a></li>
                                    <li><a href="{% url 'core:settings' %}">Ajustes</a></li>
                                    <li><a href="{% url 'core:logout' %}">Cerrar Sesión</a></li>
                                </ul>
                            </li>
                        </ul>
                        <a href="#" data-target="slide-out" class="sidenav-trigger">
                            <i class="material-icons">menu</i></a>
                    </div>
                    <div class="card" id="notifications-container">
                        <div>
                            <div class="row">
                                <div class="col s6">
                                    <h6 style="color: #6b6f82">Notificaciones</h6>
                                </div>
                                <div class="col s6">
                                    <div class="input-field">
                                        <select>
                                            <option value="0">Todas</option>
                                            <option value="1">Leidas</option>
                                            <option value="2">No Leidas</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="divider col s12" style="margin: 5px 0"></div>
                                <div class="col s12">
                                    <a class="black-text" href="#">
                                        <span class="material-icons icon-bg-circle cyan small">build</span>
                                        Notificacion de sistema!
                                    </a>
                                </div>
                                <div class="col s12">
                                    <a class="black-text" href="#">
                                        <span class="material-icons icon-bg-circle cyan small">build</span>
                                        Notificacion de sistema!
                                    </a>
                                </div>
                                <div class="col s12">
                                    <a class="black-text" href="#">
                                        <span class="material-icons icon-bg-circle cyan small">build</span>
                                        Notificacion de sistema!
                                    </a>
                                </div>
                                <div class="col s12">
                                    <a class="black-text" href="#">
                                        <span class="material-icons icon-bg-circle cyan small">gavel</span>
                                        Notificaion de proceso
                                    </a>
                                </div>
                                <div class="col s12">
                                    <a class="black-text" href="#">
                                        <span class="material-icons icon-bg-circle cyan small">gavel</span>
                                        Notificaion de proceso
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
            <!-- END NAVBAR STRUCTURE -->

            <!-- SIDENAV STRUCTURE -->

            <aside>
                <ul class="sidenav" id="slide-out">
                    <li>
                        <div class="user-view">
                            <div class="background">
                                <img src="{% static 'img/sidenav.svg' %}" alt="backgroud-sidenav">
                            </div>
                            <img class="circle" src="{% static 'img/company_logo.png' %}" alt="company-logo">
                            <span class="white-text h3">Almacenajes Mínidepositos</span>
                        </div>
                    </li>
                    <li>
                        <a href="{% url 'workflow:compra:index' %}">
                            <i class="material-icons left">attach_file</i>
                            Pendientes
                        </a>
                    </li>
                    <li><a href="#"><i class="material-icons left">assignment_turned_in</i> Completadas</a></li>
                    <li><a href="#"><i class="material-icons left">assignment_turned_in</i> Búsqueda</a></li>
                    <li><a href="#"><i class="material-icons left">description</i> Informes</a></li>
                    <li><a href="{% url 'core:settings' %}"><i class="material-icons left">build</i> Administracion</a>
                    </li>
                </ul>
            </aside>
            <!-- END SIDENAV STRUCTURE -->
        {% endblock header %}
    </header>

    <main>
        {% block main %}
            {% block main_content %}
                <div class="content">
                    {% block content %}{% endblock %}
                </div>
            {% endblock main_content %}
        {% endblock %}
    </main>
{% endblock body %}
<!--Import JS-->
{% block js %}{% include 'includes/js_includes.html' %}{% endblock js %}
{% block extrajs %}{% endblock extrajs %}
</body>
</html>